version: '3'

services: 
  db:
    image: mysql:5.6.47
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports: 
      - '3306:3306'
    environment: 
      MYSQL_DATABASE: payways_development
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_USER: root
      MYSQL_PASSWORD: MYSQL_ROOT_PASSWORD
    volumes:
      - mysql-data:/var/lib/mysql
  
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    depends_on: 
      - db
    ports:
      - '3000:3000'
    volumes: 
      - .:/documents/portfolio/payways
  
volumes: 
  mysql-data:
    driver: local

